spring.application.name=spring-data-mongo
spring.data.mongodb.uri=mongodb+srv://rennen:LLEs3JVEVsGJYzUT@devtest.euimyza.mongodb.net/?retryWrites=true&w=majority&appName=DevTest
spring.data.mongodb.database=demoDB